# apache入りのphpをインストール
FROM php:7.2-apache

# インストール可能パッケージ一覧の更新、PHP標準拡張インストローラー、sql接続のためのやつ(2つのうちどっちでもいい)、マルチバイト対応のなにか
RUN apt-get update \
    && apt-get install -y libonig-dev libzip-dev unzip \
    && docker-php-ext-install mbstring zip bcmath \
    && pecl install xdebug \
    && docker-php-ext-enable xdebug

# composer のインストール
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer
ENV COMPOSER_ALLOW_SUPERUSER 1

# お決まりの位置らしい
WORKDIR /var/www/html

# コンテナのポート、ホストOS側のは指定していない
EXPOSE 80